export const PLANS = [
{
id: "anatomie-de-loeil-et-du-systeme-de-la-vision",
title: "Anatomie de l'œil et du système de la vision",
headings: [
{ text: "I- Le globe oculaire", level: 0 },
{ text: "I-I-1- Généralité", level: 1 },
{ text: "a- Description", level: 2 },
{ text: "b- Constitution", level: 2 },
{ text: "c- Topographie de l'œil", level: 2 },
{ text: "I-2- La sclère", level: 1 },
{ text: "I-3- La cornée", level: 1 },
{ text: "I-4- Le limbe de la cornée", level: 1 },
{ text: "I-5- L'angle irido-cornéen", level: 1 },
{ text: "I-6- L'iris: uvée antérieure", level: 1 },
{ text: "I-7- Le corps ciliaire: uvée intermédiaire", level: 1 },
{ text: "I-8- La choroïde: uvée postérieure", level: 1 },
{ text: "I-9- La rétine", level: 1 },
{ text: "a- La macula", level: 2 },
{ text: "c- Structure de la rétine", level: 2 },
{ text: "d- Anatomie fonctionnelle de la rétine", level: 2 },
{ text: "e- Fonction de la rétine", level: 2 },
{ text: "f- Vascularisation de la rétine", level: 2 },
{ text: "g- Nutrition et innervation de la rétine", level: 2 },
{ text: "h- Pathologies de la rétine", level: 2 },
{ text: "I-10- Les milieux transparents", level: 1 },
{ text: "a- L'humeur aqueuse", level: 2 },
{ text: "b- Le cristallin", level: 2 },
{ text: "c- Pathologies du cristallin", level: 2 },
{ text: "d- Le vitré", level: 2 },
{ text: "d- Pathologie du vitré", level: 2 },
{ text: "II- Les voies optiques", level: 0 },
{ text: "II-1- Le nerf optique", level: 1 },
{ text: "a- La papille optique", level: 2 },
{ text: "II-2- Le chiasma optique", level: 1 },
{ text: "II-3- Les bandelettes optiques", level: 1 },
{ text: "II-4- Les radiations optiques", level: 1 },
{ text: "II-5- L'aire visuelle", level: 1 },
{ text: "III- L'orbite", level: 0 },
{ text: "IV- Les paupières", level: 0 },
{ text: "V- La conjonctive", level: 0 },
{ text: "VI- L'appareil lacrymal", level: 0 },
{ text: "VI-1- La glande lacrymale", level: 1 },
{ text: "VI-2- Les voies lacrymales", level: 1 },
{ text: "a- Drainage des larmes", level: 2 },
{ text: "b- Pathologies voies lacrymales", level: 2 },
{ text: "VII- Les muscles et nerfs oculo-moteurs", level: 0 },
{ text: "VII-1- Les muscles oculomoteurs", level: 1 },
{ text: "VII-2- Les nerfs oculo-moteurs", level: 1 },
]
},
{
  id: "hemorragies-digestives-chez-ladulte",
  title: "Hemorragies Digestives (HD) Chez L'Adulte",
  headings: [
    { text: "INTRODUCTION", level: 0 },
    { text: "Définition", level: 1 },
    { text: "Intérêts", level: 1 },
    { text: "I. DEMARCHE DIAGNOSTIQUE", level: 0 },
    { text: "Interrogatoire", level: 1 },
    { text: "Terrain", level: 2 },
    { text: "Antécédents", level: 2 },
    { text: "Caractéristiques", level: 2 },
    { text: "Signes associés", level: 2 },
    { text: "Examen physique", level: 1 },
    { text: "Paramètres vitaux", level: 2 },
    { text: "Examen appareil cutanéo-muqueux", level: 2 },
    { text: "Examen appareil digestif", level: 2 },
    { text: "Examen complet", level: 2 },
    { text: "Examens paracliniques", level: 1 },
    { text: "1ère intention : En urgence", level: 2 },
    { text: "2ème intention", level: 2 },
    { text: "II. DIAGNOSTIC", level: 0 },
    { text: "Diagnostic positif", level: 1 },
    { text: "Diagnostic différentiel", level: 1 },
    { text: "Hématémèse", level: 2 },
    { text: "Méléna", level: 2 },
    { text: "Rectorragie", level: 2 },
    { text: "Diagnostic de gravité", level: 1 },
    { text: "Diagnostic étiologique", level: 1 },
    { text: "HEMORRAGIE DIGESTIVE HAUTE", level: 2 },
    { text: "Œsophage", level: 3 },
    { text: "Cardia", level: 3 },
    { text: "Estomac", level: 3 },
    { text: "Duodénum", level: 3 },
    { text: "Autres", level: 3 },
    { text: "HEMORRAGIE DIGESTIVE BASSE", level: 2 },
    { text: "Extériorisation HD haute", level: 3 },
    { text: "Grêle", level: 3 },
    { text: "Colo-rectal", level: 3 },
    { text: "Anale", level: 3 },
    { text: "CONCLUSION", level: 0 },
    { text: "REFERENCES", level: 0 },
  ]
},
{
  id: "semeiologie-de-lappareil-respiratoire",
  title: "SEMEIOLOGIE DE L'APPAREIL RESPIRATOIRE",
  headings: [
    { text: "Introduction", level: 0 },
    { text: "Interrogatoire", level: 0 },
    { text: "INTERROGATOIRE", level: 1 },
    { text: "Généralité", level: 2 },
    { text: "Identité du patient", level: 2 },
    { text: "Motif de consultation", level: 2 },
    { text: "Antécédents", level: 2 },
    { text: "Antécédents personnels", level: 3 },
    { text: "Antécédents familiaux", level: 3 },
    { text: "Histoire de la maladie", level: 2 },
    { text: "Toux", level: 3 },
    { text: "Expectoration", level: 3 },
    { text: "Hémoptysie", level: 3 },
    { text: "Douleur thoracique", level: 3 },
    { text: "Dyspnée", level: 3 },
    { text: "Autres signes : Ronflement", level: 3 },
    { text: "Autres signes : Dysphonie", level: 3 },
    { text: "Autres signes : Hoquet", level: 3 },
    { text: "Examen clinique", level: 0 },
    { text: "Examen Clinique", level: 1 },
    { text: "Signes généraux", level: 2 },
    { text: "Asthénie", level: 3 },
    { text: "Anorexie", level: 3 },
    { text: "Amaigrissement", level: 3 },
    { text: "Fièvre", level: 3 },
    { text: "Signes physiques", level: 2 },
    { text: "Inspection", level: 3 },
    { text: "Palpation", level: 3 },
    { text: "Percussion", level: 3 },
    { text: "Auscultation", level: 3 },
  ]
},
{
  id: "syndrome-clinique-respiratoire",
  title: "SYNDROME CLINIQUE RESPIRATOIRE",
  headings: [
    { text: "INTRODUCTION", level: 0 },
    { text: "Définition", level: 1 },
    { text: "Rappels anatomiques", level: 1 },
    { text: "SYNDROME DE CONDENSATION", level: 1 },
    { text: "Définition", level: 2 },
    { text: "Types", level: 2 },
    { text: "Causes", level: 2 },
    { text: "SYNDROME BRONCHIQUE", level: 0 },
    { text: "Définition", level: 1 },
    { text: "Signes physiques", level: 1 },
    { text: "Causes", level: 1 },
    { text: "SYNDROMES PLEURAUX", level: 0 },
    { text: "PLEURESIE", level: 1 },
    { text: "PNEUMOTHORAX", level: 1 },
    { text: "SYNDROME MEDIASTINAL", level: 0 },
    { text: "Généralité", level: 1 },
    { text: "Manifestations nerveuses", level: 1 },
    { text: "Manifestations vasculaires : « Syndrome cave supérieure »", level: 1 },
    { text: "Manifestations digestives", level: 1 },
    { text: "SYNDROME DE DETRESSE RESPIRATOIRE", level: 0 },
    { text: "SDRA", level: 1 },
    { text: "Définition", level: 2 },
    { text: "Signes fonctionnels", level: 2 },
    { text: "Signes physiques", level: 2 },
    { text: "Signes de lutte respiratoire", level: 2 },
    { text: "Signes d’hypoxémie ( signe de gravité)", level: 2 },
    { text: "Signes d’hypercapnie (signe de gravité)", level: 2 },
    { text: "Signes de retentissement de SDRA", level: 2 },
    { text: "Causes", level: 2 },
  ]
},
{
  id: "examens-biologiques-essentiels-en-pneumologie",
  title: "EXAMENS BIOLOGIQUES ESSENTIELS EN PNEUMOLOGIE",
  headings: [
    { text: "INTRODUCTION", level: 0 },
    { text: "EXAMENS BIOLOGIQUES DES INFECTIONS BRONCHO-PULMONAIRES", level: 1 },
    { text: "Types de prélèvements", level: 3 },
    { text: "Examen cytobactériologique des crachats (ECBC)", level: 3 },
    { text: "Biologie moléculaire", level: 3 },
    { text: "Diagnostic bactériologique tuberculose", level: 3 },
    { text: "Diagnostic bactériologique légionellose", level: 3 },
    { text: "Diagnostic microbiologique de l'aspergillose", level: 3 },
    { text: "Diagnostic microbiologique de COVID 19", level: 3 },
    { text: "EXPLORATION DU LIQUIDE PLEURAL", level: 0 },
    { text: "LIQUIDE PLEURAL", level: 1 },
    { text: "Analyses biochimiques 1ére intention", level: 3 },
    { text: "Analyses biochimiques 2ème intention", level: 3 },
    { text: "Analyses bactériologiques", level: 3 },
    { text: "Analyses cytologiques et immunologiques", level: 3 },
    { text: "AUTRES", level: 1 },
    { text: "NFS, CRP: syndrome inflammatoire (infection)", level: 3 },
  ]
},
{
  id: "vomissements",
  title: "Vomissements",
  headings: [
    { text: "! Définition", level: 2 },
    { text: "– Rejet par la bouche du contenu gastrique c’est-à-", level: 3 },
    { text: "! Gravité : complications", level: 2 },
    { text: "– Déshydratation (eau, électrolytes)", level: 3 },
    { text: "Diagnostic positif", level: 0 },
    { text: "= définition", level: 3 },
    { text: "Diagnostic de gravité", level: 0 },
    { text: "– Deshydratation (cf supra)", level: 3 },
    { text: "Diagnostic différentiel", level: 0 },
    { text: "! Régurgitation", level: 3 },
    { text: "Diagnostic étiologique", level: 0 },
    { text: "A.   Démarche diagnostique", level: 3 },
    { text: "A. Démarche diagnostique", level: 2 },
    { text: "Interrogatoire", level: 3 },
    { text: "! Signes associés", level: 3 },
    { text: "! Antécédents", level: 3 },
    { text: "Examen physique", level: 3 },
    { text: "Examens complémentaires", level: 3 },
    { text: "B. Étiologies", level: 2 },
    { text: "! Vomissements aigus", level: 3 },
    { text: "Causes                                        Causes", level: 2 },
    { text: "Vomissements aigus", level: 3 },
    { text: "Causes digestives", level: 2 },
    { text: "Gastroentérite aigue", level: 3 },
    { text: "Occlusion intestinale aigue", level: 2 },
    { text: "! Clinique : douleur abdominale aigue,", level: 3 },
    { text: "27", level: 2 },
    { text: "Péritonite aigue", level: 2 },
    { text: "! Clinique : douleur abdominale aigue,", level: 3 },
    { text: "29", level: 2 },
    { text: "Colique hépatique", level: 2 },
    { text: "! Clinique : douleur hypochondre droit", level: 3 },
    { text: "Pancréatite aigue", level: 2 },
    { text: "! Clinique : douleur épigastrique transfixiante", level: 3 },
    { text: "Causes neurologiques", level: 2 },
    { text: "Syndrome labyrinthique", level: 3 },
    { text: "Migraine", level: 2 },
    { text: "! Clinique : céphalée hémicranienne, pulsatile,", level: 3 },
    { text: "Méningite", level: 2 },
    { text: "! Clinique : céphalée, fièvre, raideur méningée", level: 3 },
    { text: "Hypertension intra-crânienne (HTIC)", level: 2 },
    { text: "! Clinique : céphalée, vomissement en jet", level: 3 },
    { text: "Hémorragie méningée", level: 2 },
    { text: "! Clinique : céphalée ictale souvent après effort", level: 3 },
    { text: "Causes toxiques et", level: 2 },
    { text: "! Médicamenteuses", level: 3 },
    { text: "Causes métaboliques et", level: 2 },
    { text: "Grossesse", level: 3 },
    { text: "Diabète décompensé : acidocétose", level: 2 },
    { text: "! Clinique : odeur cétonique de l’haleine", level: 3 },
    { text: "Insuffisance rénale aigue", level: 2 },
    { text: "! Clinique : oligurie", level: 3 },
    { text: "Hypercalcémie", level: 2 },
    { text: "! Clinique : asthénie, somnolence", level: 3 },
    { text: "Insuffisance surrénalienne aigue", level: 2 },
    { text: "! Clinique : douleur abdominale aigue,", level: 3 },
    { text: "Autres", level: 2 },
    { text: "Mal des transports", level: 3 },
    { text: "Colique néphrétique", level: 2 },
    { text: "! Clinique : douleur fosse lombaire", level: 3 },
    { text: "Syndrome coronarien aigu", level: 2 },
    { text: "! Clinique : douleur épigastrique ou précordiale", level: 3 },
    { text: "Glaucome aigu", level: 2 },
    { text: "! Clinique : céphalée, œil rouge douloureux", level: 3 },
    { text: "Vomissements", level: 3 },
    { text: "Maladie ulcéreuse gastro-duodénale", level: 3 },
    { text: "Sténose pylorique ou bulbaire", level: 2 },
    { text: "! Clinique : vomissement d’aliments ingérés la", level: 3 },
    { text: "Gastroparésie", level: 2 },
    { text: "! Clinique : vomissement", level: 3 },
    { text: "HTIC (cf supra)", level: 3 },
    { text: "Cf supra", level: 3 },
    { text: "Insuffisance surrénalienne aigue (cf supra)", level: 3 },
    { text: "Causes psychiatriques et", level: 2 },
    { text: "Boulimie", level: 3 },
    { text: "! Diagnostic clinique", level: 2 },
    { text: "! Gravité", level: 3 },
  ]
},
{
  id: "syndrome-radiologique-thoracique",
  title: "SYNDROME RADIOLOGIQUE THORACIQUE",
  headings: [
    { text: "INTRODUCTION", level: 1 },
    { text: "Définition", level: 3 },
    { text: "Types", level: 3 },
    { text: "SYNDROME PARENCHYMATEUX", level: 1 },
    { text: "Définition", level: 3 },
    { text: "Types", level: 3 },
    { text: "1. SYNDROME ALVÉOLAIRE", level: 1 },
    { text: "Définition", level: 3 },
    { text: "Caractéristiques", level: 3 },
    { text: "2. SYNDROME INTERSTITIEL", level: 1 },
    { text: "Définition", level: 3 },
    { text: "Caractéristiques", level: 3 },
    { text: "Atteinte tissus interstitiels SOUS PLEURAUX", level: 3 },
    { text: "Atteinte tissus interstitiels PERI LOBULAIRES", level: 3 },
    { text: "Atteinte des tissus interstitiels AXIAUX ou PERI BRONCHO", level: 3 },
    { text: "3. SYNDROME CAVITAIRE", level: 1 },
    { text: "Définition : Atteinte du parenchyme avec formation de cavité", level: 3 },
    { text: "Image en Grelot", level: 3 },
    { text: "Bulle d’emphysème", level: 3 },
    { text: "SYNDROME BRONCHIQUE", level: 1 },
    { text: "Définition : ensemble signes radiologiques qui traduisent une anomalie", level: 3 },
    { text: "Épaississements des parois bronchiques", level: 3 },
    { text: "Dilatations des bronches ou bronchiectasies", level: 3 },
    { text: "Atélectasie: diminution volume pulmonaire par collapsus des alvéoles", level: 3 },
    { text: "Atélectasie", level: 3 },
    { text: "SYNDROME PLEURAL", level: 1 },
    { text: "Définition", level: 3 },
    { text: "1. PLEURÉSIE", level: 1 },
    { text: "Définition: présence de liquide dans la cavité pleurale", level: 3 },
    { text: "Types: pleurésie de faible abondance", level: 3 },
    { text: "Types: pleurésie de moyenne abondance", level: 3 },
    { text: "Types", level: 3 },
    { text: "2. PNEUMOTHORAX", level: 1 },
    { text: "Définition: présence de l’air dans la cavité pleurale", level: 3 },
    { text: "3. HYDRO-PNEUMOTHORAX", level: 1 },
    { text: "En position debout => Niveau hydro aérique", level: 3 },
    { text: "4. EPAISSISSEMENTS PLEURAUX", level: 1 },
    { text: "4 EPAISSISSEMENT PLEURAL", level: 1 },
    { text: "Définition: correspond à une augmentation anormale de l’épaisseur de", level: 3 },
    { text: "Définition", level: 3 },
    { text: "SYNDROME PARIÉTAL", level: 1 },
    { text: "Caractéristiques", level: 3 },
    { text: "Déformations rachidiennes", level: 3 },
    { text: "Atteintes costales", level: 3 },
    { text: "SYNDROME MÉDIASTINAL", level: 1 },
    { text: "Définition", level: 3 },
    { text: "Opacité médiatisnale", level: 3 },
  ]
},
{
  id: "endoscopie-bronchique",
  title: "ENDOSCOPIE BRONCHIQUE",
  headings: [
    { text: "INTRODUCTION", level: 0 },
    { text: "Définition", level: 3 },
    { text: "Intérêts", level: 3 },
    { text: "On visualise successivement", level: 3 },
    { text: "MATERIELS", level: 1 },
    { text: "Matériels utilisés: 2 types", level: 3 },
    { text: "Endoscopes rigides ou bronchoscopes rigides", level: 3 },
    { text: "Endoscopes souples ou fibroscopes", level: 3 },
    { text: "15", level: 2 },
    { text: "Video- endoscope", level: 3 },
    { text: "RÉALISATION DE L’EXAMEN", level: 1 },
    { text: "Principes", level: 3 },
    { text: "Anesthésie locale ++", level: 3 },
    { text: "Endoscopie souple sous anesthésie locale", level: 3 },
    { text: "Appréciation", level: 3 },
    { text: "INDICATIONS", level: 0 },
    { text: "Endoscopie diagnostique (endoscopie souple)", level: 3 },
    { text: "Endoscopie interventionnelle", level: 3 },
    { text: "CONTRES INDICATIONS", level: 1 },
    { text: "Absolues                               Relatives", level: 3 },
    { text: "COMPLICATIONS", level: 0 },
    { text: "Rares, mise en jeu pronostic vital rare", level: 3 },
    { text: "Surdosages en Lidocaïne: troubles neurologiques (délire), troubles", level: 3 },
  ]
},
{
  id: "explorations-fonctionnelles-respiratoires",
  title: "EXPLORATIONS FONCTIONNELLES RESPIRATOIRES",
  headings: [
    { text: "INTRODUCTION", level: 1 },
    { text: "Définition EFR", level: 3 },
    { text: "Classification des EFR", level: 3 },
    { text: "SPIROMETRIE", level: 1 },
    { text: "Définition", level: 3 },
    { text: "Indications", level: 3 },
    { text: "Contres indications", level: 3 },
    { text: "Conditions de réalisation", level: 3 },
    { text: "Technique", level: 3 },
    { text: "Résultats", level: 3 },
    { text: "Qualités de l’examen", level: 3 },
    { text: "Interprétation", level: 3 },
    { text: "Interprétation : démarche", level: 3 },
    { text: "Causes : atteintes des parenchymes pulmonaires", level: 3 },
    { text: "Causes : atteintes extra-pulmonaires", level: 3 },
    { text: "Causes", level: 3 },
    { text: "PLETHYSMOGRAPHIE CORPORELLE", level: 1 },
    { text: "PLETHYSMOGRAPHIE", level: 1 },
    { text: "Définition", level: 3 },
    { text: "Objectifs", level: 3 },
    { text: "Indications", level: 3 },
    { text: "Principe", level: 3 },
    { text: "Résultats", level: 3 },
    { text: "TRANSFERT DE CO (DLCO)", level: 1 },
    { text: "DLCO", level: 1 },
    { text: "Définition", level: 3 },
    { text: "Objectifs", level: 3 },
    { text: "Principes", level: 3 },
    { text: "Résultats", level: 3 },
    { text: "Causes", level: 3 },
    { text: "GAZOMETRIE ARTERIELLE", level: 1 },
    { text: "GAZOMETRIE", level: 1 },
    { text: "Définition", level: 3 },
    { text: "Paramètres mesurés et valeurs normales", level: 3 },
    { text: "Sites de ponction", level: 3 },
    { text: "Indications", level: 3 },
    { text: "Contre-indications", level: 3 },
    { text: "Test d’Allen", level: 3 },
    { text: "Test d’Allen : déroulements", level: 3 },
    { text: "Test d’Allen : Résultats", level: 3 },
    { text: "Technique de prélèvement", level: 3 },
    { text: "Interprétation du résultat", level: 3 },
    { text: "Lien Spirometrie et gaz du sang", level: 3 },
    { text: "EPREUVE D’EFFORT RESPIRATOIRE", level: 1 },
    { text: "EPREUVE D’EFFORT", level: 1 },
    { text: "Définition", level: 3 },
    { text: "2 Types", level: 3 },
    { text: "VO2 Max (consommation maximale d’O2 à l’effort)", level: 3 },
    { text: "VO2 Max", level: 3 },
    { text: "Test de marche de 6minutes (TM6)", level: 3 },
    { text: "Test de marche de 6 minutes (TM6)", level: 3 },
    { text: "Test de marche de 6minues (TM6)", level: 3 },
    { text: "CONCLUSION", level: 1 },
  ]
},
{
  id: "ascite",
  title: "Ascite",
  headings: [
    { text: "Généralités", level: 0 },
    { text: "Définition : accumulation d’un excès de liquide", level: 3 },
    { text: "Urgence diagnostique", level: 3 },
    { text: "Quatre mécanismes physiopathologiques", level: 3 },
    { text: "Diagnostic positif", level: 0 },
    { text: "Clinique", level: 3 },
    { text: "Paraclinique", level: 3 },
    { text: "Technique de la ponction d’ascite", level: 3 },
    { text: "Ponction proprement dite", level: 3 },
    { text: "Diagnostic de gravité", level: 0 },
    { text: "Compression du diaphragme : dyspnée", level: 3 },
    { text: "Diagnostic différentiel", level: 0 },
    { text: "Devant une augmentation du volume", level: 3 },
    { text: "A. Démarche diagnostique", level: 2 },
    { text: "1. Interrogatoire", level: 3 },
    { text: "2. Examen physique", level: 3 },
    { text: "3. Examens paracliniques", level: 3 },
    { text: "Diagnostic étiologique", level: 0 },
    { text: "B. Etiologies", level: 3 },
    { text: "Conclusion", level: 0 },
    { text: "Ascite : accumulation d’un excès de liquide", level: 3 },
    { text: "Pour en savoir plus", level: 2 },
    { text: "Traité de Gastroentérologie. 2ème édition.", level: 3 },
  ]
},
{
  id: "douleurs-abdominales-aigues-de",
  title: "Douleurs abdominales aigues de",
  headings: [
    { text: "Introduction", level: 0 },
    { text: "! Définition", level: 3 },
    { text: "Diagnostic positif", level: 0 },
    { text: "! = définition", level: 3 },
    { text: "Diagnostic de gravité", level: 0 },
    { text: "1. Occlusion intestinale aiguë", level: 3 },
    { text: "2.   Péritonite aiguë", level: 3 },
    { text: "Diagnostic étiologique", level: 0 },
    { text: "A.   Démarche diagnostique", level: 3 },
    { text: "1.   Interrogatoire : histoire de la maladie", level: 3 },
    { text: "1.   Interrogatoire : antécédents", level: 3 },
    { text: "2.   Examen physique", level: 3 },
    { text: "3.   Examens paracliniques", level: 3 },
    { text: "Douleur'", level: 3 },
    { text: "Causes&", level: 3 },
    { text: "Péritonite aigue", level: 3 },
    { text: "Occlusion intestinale aigue", level: 3 },
    { text: "Epigastre", level: 3 },
    { text: "Maladie ulcéreuse gastro-duodénale", level: 3 },
    { text: "Gastrite ou duodénite aigue", level: 3 },
    { text: "Dyspepsie", level: 3 },
    { text: "Pancréatite aigue", level: 3 },
    { text: "Syndrome coronarien aigu", level: 3 },
    { text: "Hypochondre+droit", level: 3 },
    { text: "Cholécystite aigue ou migration de lithiase", level: 3 },
    { text: "!   Pancréatite aigue (Cf supra)", level: 3 },
    { text: "Flanc&droit                         Flanc&gauche", level: 3 },
    { text: "Colique néphrétique ou infection urinaire", level: 3 },
    { text: "Fosse%iliaque%", level: 3 },
    { text: "Appendicite aigue", level: 3 },
    { text: "Pathologies annexielles", level: 3 },
    { text: "Hypogastre", level: 3 },
    { text: "Grossesse extra-utérine", level: 3 },
    { text: "Diverticulite sigmoïdienne", level: 3 },
    { text: "!   Pathologie annexielle (Cf supra)", level: 3 },
    { text: "Hypochondre+", level: 3 },
    { text: "Région'péri*", level: 3 },
    { text: "!   Péritonite aigue (Cf supra)", level: 3 },
    { text: "Acidocétose diabétique", level: 3 },
    { text: "Insuffisance surrénalienne aigue", level: 3 },
    { text: "Crise drépanocytaire", level: 3 },
    { text: "Conclusion", level: 0 },
    { text: "Douleur abdominale", level: 3 },
  ]
},
{
  id: "dysphagie",
  title: "Dysphagie",
  headings: [
    { text: "! Définition", level: 2 },
    { text: "– Gêne ou obstacle lors de la déglutition", level: 3 },
    { text: "Diagnostic positif", level: 0 },
    { text: "! Évoqué à la clinique = définition", level: 3 },
    { text: "Diagnostic de gravité", level: 0 },
    { text: "! Signes de déshydratation", level: 3 },
    { text: "! Signes de dénutrition", level: 3 },
    { text: "Diagnostic étiologique", level: 0 },
    { text: "A- Démarche diagnostique", level: 3 },
    { text: "A. Démarche diagnostique", level: 2 },
    { text: "1-Interrogatoire", level: 3 },
    { text: "! Antécédents", level: 3 },
    { text: "2-Examen physique", level: 3 },
    { text: "3-Examens complémentaires", level: 3 },
    { text: "! Transit baryté : indiqué si", level: 3 },
    { text: "! Scanner thoracique", level: 3 },
    { text: "Dysphagie", level: 3 },
    { text: "! Dysphagie organique", level: 3 },
    { text: "! Dysphagie fonctionnelle", level: 3 },
    { text: "B. Etiologies : D organique", level: 2 },
    { text: "Cancer de l’œsophage", level: 3 },
    { text: "Sténose peptique", level: 3 },
    { text: "Œsophagite", level: 3 },
    { text: "Œsophagite caustique", level: 3 },
    { text: "Autres", level: 3 },
    { text: "Tumeurs bronchiques", level: 3 },
    { text: "Adénopathies ou tumeurs", level: 3 },
    { text: "B. Etiologies : D fonctionnelle", level: 2 },
    { text: "Achalasie ou mégaoesophage", level: 3 },
    { text: "Spasmes diffus de l’œsophage", level: 3 },
    { text: "Causes neurologiques : diabète,", level: 3 },
    { text: "Sclérodermie, dermatomyosite", level: 3 },
  ]
},
{
  id: "examen-de-lappareil-digestif",
  title: "Examen de l’appareil digestif",
  headings: [
    { text: "Objectif", level: 2 },
    { text: "! Maîtriser les 5 temps de l’examen de l’appareil", level: 3 },
    { text: "Inspection", level: 0 },
    { text: "! De la bouche à l’anus", level: 3 },
    { text: "! Cavité buccale", level: 3 },
    { text: "! Abdomen", level: 3 },
    { text: "Palpation", level: 0 },
    { text: "! Technique", level: 3 },
    { text: "Epigastre", level: 2 },
    { text: "Hypochondre", level: 3 },
    { text: "! Résultats", level: 3 },
    { text: "Percussion", level: 0 },
    { text: "! Technique", level: 3 },
    { text: "! Résultats", level: 3 },
    { text: "! Taille du foie (flèche hépatique)", level: 3 },
    { text: "Auscultation", level: 0 },
    { text: "! Bruits hydro- aériques", level: 3 },
    { text: "Toucher rectal", level: 0 },
    { text: "! Technique", level: 3 },
    { text: "! Résultats", level: 3 },
    { text: "Points forts", level: 2 },
    { text: "! Toujours respecter les 5 temps de l’examen de", level: 3 },
  ]
},
{
  id: "exploration-du-foie-et-des-voies",
  title: "Exploration du foie et des voies",
  headings: [
    { text: "Biochimie", level: 2 },
    { text: "! Cytolyse : destruction des hépatocytes", level: 3 },
    { text: "! Insuffisance hépato-cellulaire : réduction ou", level: 3 },
    { text: "! Cholestase : écoulement biliaire", level: 3 },
    { text: "! Inflammation", level: 3 },
    { text: "Anatomie pathologique", level: 2 },
    { text: "! Ponction biopsie hépatique", level: 3 },
    { text: "Abdomen sans préparation de", level: 2 },
    { text: "! Coupole diaphragmatique", level: 3 },
    { text: "Echographie abdominale", level: 0 },
    { text: "! Foie", level: 3 },
    { text: "! Vésicule biliaire", level: 3 },
    { text: "! Voies biliaires intra (VBIH) et extra-hépatiques", level: 3 },
    { text: "Scanner abdominal", level: 0 },
    { text: "! Sans et avec injection de produit de contraste", level: 3 },
    { text: "Imagerie par résonance magnétique", level: 0 },
    { text: "(IRM) abdominale", level: 3 },
    { text: "Explorations endoscopiques", level: 0 },
    { text: "! Echoendoscopie bilio-pancréatique : veine", level: 3 },
  ]
},


];